version: '3.8'

services:
  app:
    container_name: edu-forge-notification
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    environment:
      - HUSKY=0
      - CI=true
      - DATABASE_URL=mongodb://root:123456@mongodb:27017/user?authSource=admin
      - NODE_ENV=production
    ports:
      - "3006:3006"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - notification-network
    restart: unless-stopped

networks:
  notification-network:
    name: edu-forge-notification-network123
    driver: bridge

volumes:
  mongodb_data:
    name: edu-forge-mongodb-data
    driver: local