version: '3.8'

services:
  app:
    container_name: edu-forge-notification
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - '3000'
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=mongodb://mongodb:27017/edu-forge-notification?replicaSet=rs0
      - PORT=3000
      - CORS_ORIGIN=*
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL:-notifications@eduforge.io.vn}
      - HUSKY=0
      - CI=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - edu-forge-network
    restart: unless-stopped

  mongodb:
    container_name: edu-forge-mongodb
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - edu-forge-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-init:
    container_name: edu-forge-mongo-init
    image: mongo:latest
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval "
        rs.initiate({
          _id: 'rs0',
          members: [{ _id: 0, host: 'mongodb:27017' }]
        });
      "
    networks:
      - edu-forge-network

networks:
  edu-forge-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
