version: '3.8'

services:
  app:
    container_name: edu-forge-notification
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - HUSKY=0
      - CI=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - notification-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  mongodb:
    container_name: edu-forge-mongodb-notification
    image: mongo:latest
    command: ["--bind_ip_all", "--auth"]
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - notification-network
    restart: unless-stopped
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  mongo-init:
    container_name: edu-forge-mongo-init
    image: mongo:latest
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host edu-forge-mongodb:27017 -u ${MONGO_USER:-admin} -p ${MONGO_PASSWORD:-admin} --authenticationDatabase admin --eval "
        rs.initiate({
          _id: 'rs0',
          members: [{ _id: 0, host: 'edu-forge-mongodb:27017' }]
        });
      "
    networks:
      - notification-network

networks:
  notification-network:
    name: notification-network
    driver: bridge

volumes:
  mongodb_data:
    driver: local
