version: '3.8'

services:
  app:
    container_name: edu-forge-notification
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - HUSKY=0
      - CI=true
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
    ports:
      - "3006:3006"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - notification-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  mongodb:
    container_name: edu-forge-mongodb-notification
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - notification-network
    restart: unless-stopped
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

networks:
  notification-network:
    name: notification-network
    driver: bridge

volumes:
  mongodb_data:
    driver: local